import { Tool } from '../base-tool';
import { ExecutionContext, ToolResult } from '../types';
import * as fs from 'fs/promises';
import * as path from 'path';

export class SaveKnowledgeTool extends Tool {
    name = 'save_knowledge';
    description = 'Save a piece of knowledge, a lesson learned, or architectural documentation to the project memory.';
    parameters = {
        title: { type: 'string', description: 'A short, descriptive title' },
        content: { type: 'string', description: 'The detailed knowledge, guide, or documentation' },
        category: { type: 'string', enum: ['architecture', 'api', 'style', 'fix', 'workflow'], description: 'The category of the knowledge' },
        tags: { type: 'array', items: { type: 'string' }, description: 'Search keywords' }
    };

    async execute(params: any, context: ExecutionContext): Promise<ToolResult> {
        const { title, content, category, tags = [] } = params;
        const memoryDir = path.join(process.cwd(), '.nexa', 'knowledge');
        const filename = `${Date.now()}_${title.toLowerCase().replace(/\s+/g, '_')}.md`;
        const filePath = path.join(memoryDir, filename);

        try {
            await fs.mkdir(memoryDir, { recursive: true });

            const markdown = `---
title: ${title}
category: ${category}
tags: ${tags.join(', ')}
date: ${new Date().toISOString()}
---

# ${title}

${content}

---
*Generated by Nexa Agent*
`;

            await fs.writeFile(filePath, markdown, 'utf-8');

            return {
                success: true,
                data: {
                    message: `Knowledge item '${title}' saved successfully to project memory.`,
                    path: filePath
                }
            };
        } catch (error: any) {
            return {
                success: false,
                error: `Failed to save knowledge: ${error.message}`,
                data: null
            };
        }
    }
}
