import React from 'react';
import { Download, FileText, CheckCircle2 } from 'lucide-react';

interface ArtifactCardProps {
    filename: string;
    content: string;
    language?: string;
}

export default function ArtifactCard({ filename, content, language }: ArtifactCardProps) {

    const handleDownload = () => {
        const blob = new Blob([content], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    return (
        <div className="my-3 p-3 rounded-xl border border-white/10 bg-[#1e1e2e] shadow-lg flex items-center justify-between group hover:border-blue-500/30 transition-all">
            <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-lg bg-blue-500/10 flex items-center justify-center text-blue-400">
                    <FileText size={20} />
                </div>
                <div>
                    <h3 className="text-sm font-medium text-white">{filename}</h3>
                    <div className="text-xs text-blue-300/60 flex items-center gap-1">
                        <CheckCircle2 size={10} /> Generated by Agent
                    </div>
                </div>
            </div>

            <button
                onClick={handleDownload}
                className="p-2 rounded-lg bg-blue-600 hover:bg-blue-500 text-white transition-colors flex items-center gap-2 text-sm font-medium shadow-lg shadow-blue-500/20"
            >
                <Download size={16} />
                Download
            </button>
        </div>
    );
}
